name: TestsExample Android check
on:
  pull_request:
    paths:
      - .github/workflows/android-build-tests-test.yml
      - 'android/**'
      - 'src/fabric/**'
      - 'package.json'
      - 'apps/tests-example/android/**'
      - 'apps/tests-example/package.json'
  push:
    branches:
      - main
  workflow_dispatch:

uses: ./.github/workflows/android-build.yml
with:
  working-directory: 'tests-example'
