name: iOS Build Reusable
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string

jobs:
  build:
    name: 'Xcode Build'
    runs-on: macos-latest
    env:
      DEVICE: iPhone 17 Pro
    concurrency:
      group: ios-${{ inputs.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Use latest stable Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Get react-native-svg node_modules cache
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-svg-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-svg-

      - name: Install react-native-svg node_modules
        run: yarn install --frozen-lockfile

      - name: Get app node_modules cache
        uses: actions/cache@v4
        with:
          path: apps/${{ inputs.working-directory }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ inputs.working-directory }}-${{ hashFiles(format('apps/{0}/yarn.lock', inputs.working-directory)) }}
          restore-keys: ${{ runner.os }}-node-modules-${{ inputs.working-directory }}-

      - name: Install app node_modules
        working-directory: apps/${{ inputs.working-directory }}
        run: yarn install --frozen-lockfile

      - name: Get Pods cache
        uses: actions/cache@v4
        with:
          path: apps/${{ inputs.working-directory }}/ios/Pods
          key: ${{ runner.os }}-pods-${{ inputs.working-directory }}-${{ hashFiles(format('apps/{0}/ios/Podfile.lock', inputs.working-directory)) }}
          restore-keys: |
            ${{ runner.os }}-pods-${{ inputs.working-directory }}-

      - name: Install Pods
        id: install_pods
        continue-on-error: true
        working-directory: apps/${{ inputs.working-directory }}/ios
        run: bundle install && bundle exec pod install

      - if: steps.install_pods.outcome == 'failure'
        id: remove_pods
        name: Remove pods
        working-directory: apps/${{ inputs.working-directory }}/ios
        run: rm -rf build Pods Podfile.lock

      - if: steps.remove_pods.outcome == 'success'
        id: reinstall_pods
        name: Reinstall pods
        working-directory: apps/${{ inputs.working-directory }}/ios
        run: bundle install && bundle exec pod install

      - name: Get build artifacts cache
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-ios-derived-data-${{ inputs.working-directory }}-${{ hashFiles(format('apps/{0}/ios/Podfile.lock', inputs.working-directory)) }}
          restore-keys: |
            ${{ runner.os }}-ios-derived-data-${{ inputs.working-directory }}-

      - name: Build app
        working-directory: apps/${{ inputs.working-directory }}
        run: npx react-native run-ios --simulator="${{ env.DEVICE }}" --mode Debug --verbose --no-packager
