name: Reusable macOS Build

on:
  workflow_call:
    inputs:
      new_arch_enabled:
        required: true
        type: string

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        working-directory: [macos-example]
      fail-fast: false
    concurrency:
      group: macos-${{ matrix.working-directory }}-${{ github.ref  }}-${{ inputs.new_arch_enabled }}
      cancel-in-progress: true
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Restore react-native-svg node_modules from cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-svg-${{ hashFiles('yarn.lock') }}
          restore-keys: ${{ runner.os }}-node-modules-svg-

      - name: Install react-native-svg node modules
        run: yarn install

      - name: Restore app node_modules from cache
        uses: actions/cache@v3
        with:
          path: ${{ matrix.working-directory }}/node_modules
          key: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/yarn.lock', matrix.working-directory)) }}
          restore-keys: ${{ runner.os }}-node-modules-${{ matrix.working-directory }}-

      - name: Install app node modules
        working-directory: ${{ matrix.working-directory }}
        run: yarn install

      - name: Restore Pods from cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ matrix.working-directory }}/macos/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/macos/Podfile.lock', matrix.working-directory)) }}-${{ inputs.new_arch_enabled }}

      - name: Install Pods
        working-directory: ${{ matrix.working-directory }}/macos
        if: ${{ inputs.new_arch_enabled }} == 1
        run: RCT_NEW_ARCH_ENABLED=${{ inputs.new_arch_enabled }} pod install
        if: ${{ inputs.new_arch_enabled }} == 0
        run: pod install

      - name: Restore build artifacts from cache
        uses: actions/cache@v3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-macos-derived-data-${{ matrix.working-directory }}-${{ hashFiles(format('{0}/macos/Podfile.lock', matrix.working-directory)) }}-${{ inputs.new_arch_enabled }}

      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: yarn macos
